### ISSUE TITLE
Libgl1 is not installed in order to run clean.py

### ISSUE THREAD

**Issue by simon-edwards-sony** [mhw32/data-centric-deep-learning#16]
When running clean.py for the integration tests the following error is produced:
`Traceback (most recent call last):
  File "src/tests/clean.py", line 10, in <module>
    import cv2
  File "/home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory`
   
  This can be resolved by installing the libgl1 package manually:
  `sudo apt-get update && sudo apt-get install libgl1`
  
  Or better still, by including this in the dockerfile:
  `RUN sudo apt-get update && sudo apt-get install -y libgl1`

**Comment by mhw32** [comment]
Adding this into the dockerfile as part of https://github.com/mhw32/data-centric-deep-learning/pull/18
